# Generated by Django 4.1.6 on 2023-02-26 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exSeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(help_text='The png name of the avatar image', max_length=100)),
                ('avatarTitle', models.CharField(help_text='The name found under the avatar in the selection menu', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpotRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Entries',
                'verbose_name_plural': 'Register',
            },
        ),
        migrations.AlterModelOptions(
            name='previousspotattend',
            options={'verbose_name': 'Spot Records', 'verbose_name_plural': 'Spot Record'},
        ),
        migrations.RemoveField(
            model_name='spot',
            name='image_pointer',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='level',
        ),
        migrations.AddField(
            model_name='spot',
            name='desc',
            field=models.TextField(help_text='A description of the spot, to appear when a user sees the spot', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='imageName',
            field=models.CharField(blank=True, help_text='The name of the png file that holds this spots image', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='currentStreak',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The users current streak'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='totalPoints',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The users high score'),
        ),
        migrations.AlterField(
            model_name='previousspotattend',
            name='spotDay',
            field=models.DateField(db_index=True, help_text='The day that this was the spot of the day, represented as the Python datetime.date value', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='average_attendance_int',
            field=models.PositiveSmallIntegerField(default=0, help_text='The average whole number of users that come to this spot when it is spot of the day'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='group',
            field=models.CharField(blank=True, choices=[('GR', 'Green'), ('YW', 'Yellow'), ('BL', 'Blue'), ('RD', 'Red')], help_text="The user's group affiliation", max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='title',
            field=models.CharField(blank=True, help_text='The title chosen by the user to represent them', max_length=100),
        ),
        migrations.DeleteModel(
            name='CurrentSpotRegister',
        ),
        migrations.AddField(
            model_name='spotregister',
            name='psaId',
            field=models.ForeignKey(help_text='Related spot-day instance', on_delete=django.db.models.deletion.CASCADE, to='exSeed.previousspotattend', verbose_name='Spot data'),
        ),
        migrations.AddField(
            model_name='spotregister',
            name='uId',
            field=models.ForeignKey(help_text="This user has attended today's spot", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatarId',
            field=models.ForeignKey(default=1, help_text="User's chosen avatar", on_delete=django.db.models.deletion.CASCADE, to='exSeed.avatar'),
        ),
    ]
