extra_dictionary = {
    "titles": [
        "Captain Compost",
        "Eco Warrior",
        "Sir Reduce-A-Lot",
        "Sapling",
        "Tree",
        "Log",
        "Big Tree",
        "Large Trunk",
        "Leaf",
        "Green Machine",
        "Recycling Queen",
        "Recycling King",
        "Compost King",
        "Compost Queen",
        "Waste Wizard",
        "Carbon Crusader",
        "Reusable Renegade",
        "Upcycling Unicorn",
        "Renewable Rocket",
        "Energy Elf",
        "Thrift-Shop Titan",
        "Zero-Waste",
        "Pollution Punisher",
        "Eco-Enthusiast",
        "Green Guru",
        "Planet Protector",
        "Eco Explorer",
        "Green Guardian",
        "Climate Crusader",
        "Sustainable Samurai",
        "Earth Advocate",
        "Waste-Free Wonder",
        "Green Queen",
        "Green King",
        "Green-Thumbed",
        "Ocean Crusader",
        "Low-Impact Legend",
        "Greenery Gnome",
        "Green Mamba",
        "Matt Collinson",
        "The Wakinator",
        "Liam",
        "Nick The Distiller"
    ],
    "facts": ["Exeter University has committed to being carbon neutral by the year 2040.",
              "Exeter University has reduced its carbon emissions by 35% since 2005.",
              "Exeter University has been ranked in the top 10 UK universities for sustainability.",
              "Exeter University has installed over 3,000 solar panels across its campuses.",
              "Exeter University has reduced its water consumption by 30% since 2014.",
              "Exeter University has a Green Capital Fund, which exists to support sustainability projects.",
              "The UK has set a target to achieve net-zero greenhouse gas emissions by 2050, making it the first country to do so.",
              "In 2020, the UK generated more electricity from wind farms than from any other source.",
              "The UK has committed to planting 30,000 hectares of new trees per year.",
              "The UK has a National Nature Reserve system that protects over 700 sites of for wildlife.",
              "The UK is one of the world leaders in offshore wind energy, with over 10 GW of energy capability.",
              "The UK has banned the sale of microbeads, which can harm marine life and pollute the ocean.",
              "The UK has committed to reserving at least 30% of its land and seas for nature by 2030.",
              "The UK government has a £2 billion Green Homes Grant to improve the energy efficiency of homes with methods such as insulation.",
              "The UK outlawed the sale of products containing ivory to help protect endangered elephants.",
              "The UK government has launched a £3 billion plan to support the development of carbon capture technologies to reudce carbon in the atmosphere.",
              "The UK has implemented a ban on the use of neonicotinoid pesticides, which can harm bees and other pollinators.",
              "The UK has a network of over 2,000 protected areas, including national parks and areas of natural beauty.",
              "The world's largest solar power plant, in the UAE, can generate enough electricity to power 90,000 homes.",
              "China is the world's largest producer of solar panels, with 70% of global production.",
              "The Pacific Garbage Patch is currently twice the size of Texas.",
              "Norway has the highest percentage of electric cars on the road, over 50% of new cars sold in 2020 being electric.",
              "The world's largest wind turbine in denmark can generate enough electricity to power 20,000 homes.",
              "The world's oceans absorb around 25% of the carbon dioxide emitted by human activities, which raises the pH and threatening marine life.",
              "The world's first floating solar farm in the United Kingdom, can generate enough electricity to power 4,500 homes.",
              "The UK is home to over 90,000 different species of animals, plants, and fungi.",
              "There are over 25,000 species of insects in the UK.",
              "The UK has several species of seals, including the grey seal and the common seal, found along the coast.",
              "The Earth's average temperature has risen by about 1.2 degrees Celsius since the late 19th century, with the majority of this warming occurring in the past few decades.",
              "The Paris Agreement, signed by 197 countries in 2015, aims to limit global warming to well below 2 degrees Celsius above pre industrial revolution.",
              "Illegal, unreported, and unregulated fishing accounts for approximately 20% of the global catches.",
              "Sustainable fishing practices, such as using selective gear that targets specific species and avoids bycatch, can help to reduce the impact of fishing on marine ecosystems.",
              "In the U.S. alone, around 10 billion land animals and 47 billion aquatic animals are killed per year for human consumption.",
              "A hot water tap that leaks one drop per second can add up to 165 gallons a month. That's more than one person uses in two weeks.",
              "An energy-smart clothes washer can save more water in one year than one person drinks in an entire lifetime.",
              "An automatic dishwasher uses less hot water than doing dishes by hand -- an average of six gallons less.",
              "Although accounting for only 5% of the world's population, Americans consume 26% of the world's energy.",
              "A crack as small as 1/16th of an inch around a window frame can let in as much cold air as leaving the window open three inches.",
              "Every time you open the refrigerator door, up to 30% of the cold air can escape.",
              "One ton of 100% recycled paper saves the equivalent of 4,100 kWh of energy, 7,000 gallons of water, 60 pounds of air emissions and three cubic yards of landfill space.",
              "China is the world’s largest polluter emitting 10,357 tons of CO2, followed by the United States, India, Russia and Japan.",
              "Human-caused emissions of carbon dioxide need to fall 45% from 2010 levels by 2030 and reach net-zero around 2050 to limit climate change.",
              "Lighting accounts for 15% of global electricity use. Switching to LEDs will use 90% less energy and last longer than traditional bulbs.",
              "70% of the world is covered by water, yet only 2.5% of it is fresh and only 1% of it is easily accessible for humans.",
              "Water use has grown at more than twice the rate of population increase in the last 100 years.",
              "Germany has the best recycling rate in the world followed by Austria, South Korea and Wales.",
              "Recycling one ton of paper saves 17 trees.",
              "The process of Aforestation creates a carbon sink. This draws in carbon from the atmosphere and distributes it into the soil.",
              "The world dumps 2.12 billion tons of waste each year.",
              "Only 16% of the world's waste is recycled.",
              "More than 400 Million Tons of plastic waste are produced globally each year. Only 18% of plastic is collected to be recycled.",
              "The Great Pacific Garbage Patch now contains around 2 trillion pieces of plastic, including plastic bottle caps, bottles, bags, lids, containers, and cups.",
              "Plastic grocery bags take 20 years to decompose. A plastic straw can take 200 years. Plastic beverage bottles and cups can take up to 450 years. Some plastics may never biodegrade at all.",
              "Around 64 million people's lives are directly affected by the exporting and dumping of waste in poorer countries such as Ghana, Indonesia, and Pakistan.",
              "An astonishing 5 trillion plastic bags are used globally every year. Switching to reusable grocery bags could dramatically reduce this number.",
              "The world population currently uses 580 million terajoules of energy every year.",
              "Despite advances in the collection of renewable energy, 83% of global energy still comes from fossil fuels.",
              "6.59% of global electricity comes from wind power."]
}
